name: "data_pipeline"
version: "1.0.0"
config-version: 2

profile: "data_pipeline"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

flags:
  send_anonymous_usage_stats: false

models:
  data_pipeline:
    staging:
      +materialized: view
      +schema: STAGING
    intermediate:
      +schema: INTERMEDIATE
    marts:
      +materialized: table
      +schema: MARTS
